### ISSUE TITLE
NullPointerException on miscellaneous IDE actions

### ISSUE THREAD

**Issue by duponter** [eddysystems/issues#3]
Hi,

I'm getting a lot of NPE's in my event log. I cannot pin it down to a specific IDE action.
I'm using version 0.2pre-14.

Here's the stack trace:

_null
java.lang.NullPointerException
    at com.eddysystems.eddy.EddyFileListener.process(EddyFileListener.java:95)
    at com.eddysystems.eddy.EddyFileListener.documentChanged(EddyFileListener.java:264)
    at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:781)
    at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:721)
    at com.intellij.openapi.editor.impl.DocumentImpl.insertString(DocumentImpl.java:498)
    at com.intellij.openapi.editor.EditorModificationUtil.insertStringAtCaretNoScrolling(EditorModificationUtil.java:151)
    at com.intellij.openapi.editor.EditorModificationUtil.insertStringAtCaret(EditorModificationUtil.java:116)
    at com.intellij.openapi.editor.EditorModificationUtil.insertStringAtCaret(EditorModificationUtil.java:108)
    at com.intellij.openapi.editor.EditorModificationUtil.typeInStringAtCaretHonorBlockSelection(EditorModificationUtil.java:403)
    at com.intellij.codeInsight.editorActions.TypedHandler.a(TypedHandler.java:247)
    at com.intellij.codeInsight.editorActions.TypedHandler.access$100(TypedHandler.java:66)
    at com.intellij.codeInsight.editorActions.TypedHandler$1.perform(TypedHandler.java:211)
    at com.intellij.openapi.editor.impl.CaretModelImpl$3.run(CaretModelImpl.java:355)
    at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:435)
    at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:346)
    at com.intellij.codeInsight.editorActions.TypedHandler.execute(TypedHandler.java:153)
    at com.intellij.codeInsight.lookup.impl.LookupTypedHandler.execute(LookupTypedHandler.java:91)
    at com.intellij.execution.impl.ConsoleViewImpl$MyTypedHandler.execute(ConsoleViewImpl.java:1249)
    at com.intellij.openapi.editor.actionSystem.TypedAction$TypingCommand$1.run(TypedAction.java:133)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:977)
    at com.intellij.openapi.editor.actionSystem.TypedAction$TypingCommand.run(TypedAction.java:127)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
    at com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:107)
    at com.intellij.openapi.editor.impl.EditorImpl.a(EditorImpl.java:1037)
    at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:5135)
    at com.intellij.openapi.editor.impl.EditorImpl$11.keyTyped(EditorImpl.java:880)
    at java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:239)
    at java.awt.Component.processKeyEvent(Component.java:6471)
    at javax.swing.JComponent.processKeyEvent(JComponent.java:2829)
    at java.awt.Component.processEvent(Component.java:6293)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4872)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1887)
    at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:762)
    at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1027)
    at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:899)
    at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:727)
    at java.awt.Component.dispatchEventImpl(Component.java:4742)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:740)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:699)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:713)
    at java.awt.EventQueue$4.run(EventQueue.java:711)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:710)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:547)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)_

Kind regards

**Comment by martinwicke** [comment]
Mysterious again. I can hide that, and I will if we cannot find a solution. But if you don't mind, let me ask a few questions first:
- Does eddy every successfully suggest anything? Or is the NPEs basically the only thing you see?
- Do you have multiple projects open, or are you editing a file which is not part of any project?
- Does this happen for any project, or a specific one? Does this happen also if you create a new project and just edit the resulting source file?
- Are you passing custom arguments to your JVM, or do you have some custom JVM installation?

**Comment by duponter** [comment]
I think I was a little too rash with my issue report. 
Apart from that one time (where I got a NPE every 1 to 5 seconds), I am not experiencing this behaviour anymore.
I took my time to evaluate and to monitor whether I get these NPE's again, but they don't appear anymore. 
Sorry for the inconvenience.

**Comment by martinwicke** [comment]
Ok. I'm still interested in what caused this, let me know if you encounter it again. Version 0.2 should be online soon (it's pending approval), which will fix some more issues (including a safety net for this one). Because you installed from file, I am not sure you'll receive automatic updates, so it may be worth checking manually.

**Comment by duponter** [comment]
I've installed the final 0.2 version and will give it a try.
If I encounter issues again, I will report them.
